name: Go package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    services:
      redis:
        image: redis/redis-stack-server
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: go get .
      - name: Create folder
        run: mkdir -p ./web/images/articles
      - name: Populating data
        run: go run console/console.go populate
      - name: Run migration
        run: go run console/console.go migration
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
