name: Go package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    services:
      redis:
        image: redis/redis-stack-server
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping && redis-cli -h localhost -p 6379 < populate.redis"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    runs-on: ubuntu-latest
    env:
      WORKSPACE_DIR: /home/runner/work/gifthub/gifthub
      COOKIE_SECURE: 0
      EMAIL_DRY: 1
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: go get .
      - name: Create folder
        run: mkdir -p ./web/images/articles
      - name: Add Redis indexes 
        run: redis-cli -h localhost -p 6379 < migrate.redis
      - name: Build
        run: go build -v ./...
      - name: Run the unit tests
        run: go test -v ./...
      - name: Prepare functional test data 
        run: |
          redis-cli -h localhost -p 6379 < populate.redis
          redis-cli -h localhost -p 6379 < hurl.redis
      - name: Install HURL
        shell: bash
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.0.0/hurl_4.0.0_amd64.deb
          sudo apt update && sudo apt install ./hurl_4.0.0_amd64.deb
      - name: Run the functional tests
        run: |
          go run main.go &
          sleep 2 && hurl --variables-file web/hurl/admin/.env --test web/hurl/admin/*.hurl
