name: Go package

on: [push]

jobs:
  test:
    services:
      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Populating data
        run: go run console/console.go populate
      - name: Install dependencies
        run: go get . 
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./... 
