name: Go package

on: [push]

jobs:
  test:
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps port 6379 on service container to the host
          - 6379:6379

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install redis
        run: sudo apt-get install -y redis-tools redis-server
      #- name: Verify that redis is up
      #  run: redis-cli ping
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.x'
      - name: Populating data
        run: go run console/console.go populate
      - name: Install dependencies
        run: go get . 
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./... 
