name: Go package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    services:
      redis:
        image: redis/redis-stack-server
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    runs-on: ubuntu-latest
    env:
      WORKSPACE_DIR: /home/runner/work/artisons/artisons
      COOKIE_SECURE: 0
      EMAIL_DRY: 1
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21.x"
      - name: Install dependencies
        run: go install .
      - name: Create folder
        run: mkdir -p ./web/images/articles
      - name: Migrating 
        run: go run console/console.go -file web/redis/migrate.redis redis
      - name: Build
        run: go build -v ./...
      - name: Run the unit tests
        run: go test -v ./...
      - name: Populating data
        run: go run console/console.go -file web/redis/hurl.redis redis
      - name: Install HURL
        shell: bash
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/4.0.0/hurl_4.0.0_amd64.deb
          sudo apt update && sudo apt install ./hurl_4.0.0_amd64.deb
      - name: Run the functional tests
        run: |
          go run main.go &
          sleep 2
          hurl --variable time=$(date +%s) --variables-file web/hurl/.env --test web/hurl/otp/*.hurl
          hurl --variable time=$(date +%s) --variables-file web/hurl/.env --cookie web/hurl/admin/cookies.txt --test web/hurl/admin/*.hurl
          hurl --variable time=$(date +%s) --variables-file web/hurl/.env --cookie web/hurl/user/cookies.txt --test web/hurl/user/*.hurl
          hurl --variable time=$(date +%s) --variables-file web/hurl/.env --test web/hurl/*.hurl